import DisplayLetters from "@/components/displayLetters";
import Header from "@/components/header";
import Instruction from "@/components/instruction";
import { useEffect, useState } from "react";
import { Button } from "react-bootstrap";


const alphebet = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','q','r','s','t','u','v','w','x','y','z']



export default function Home() {
  // const [correctLetter, setCorrectLetter] = useState('')
  // const [otherLetters, setOtherLetters] = useState([])
  // const [shuffledArray, setShuffledArray] = useState([])
  // useEffect(() => {
  //   const randomIndex = Math.floor(Math.random() * alphebet.length);
  //   setCorrectLetter(() => alphebet[randomIndex])
  //   setOtherLetters(() => [ alphebet[randomIndex + 1], alphebet[randomIndex - 1] ])
  //   const correctLetterArray = [correctLetter]
  //   const completeArray = correctLetterArray.concat(otherLetters)
  //   setShuffledArray(() => completeArray.sort((a,b) => 0.5 - Math.random()))
  // }, [])
  const [clicked, setClicked] = useState(0)
  const randomIndex = Math.floor(Math.random() * alphebet.length);
  const correctLetter = alphebet[randomIndex].toUpperCase()
  const otherLetters = [ alphebet[randomIndex + 1].toUpperCase(), alphebet[randomIndex - 1].toUpperCase() ]
  const correctLetterArray = [correctLetter]
  const completeArray = correctLetterArray.concat(otherLetters) 
  const shuffledArray = completeArray.sort((a,b) => 0.5 - Math.random());

  function next() {
    setClicked((current) => current + 1)
    // location.reload()
  }
  // console.log('randomIndex', randomIndex);
  // console.log('correctLetter', correctLetter);
  // console.log('otherLetters', otherLetters);
  return (
    <>
      <Header />
      <Instruction correctLetter={correctLetter} />
      <DisplayLetters shuffledArray={shuffledArray} correctLett={correctLetter}/>
      <Button onClick={next}>Next</Button>

    </>
  )
}


// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Learn The Alphabet</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
